"""A3 — the algebra floor for agent-authored analytical products.

Storage-agnostic by construction: nothing in this package imports Django, neomodel or a
graph driver, and ``tests/agent_neo/a3/test_import_boundary.py`` keeps it that way.
``AGENTS.md`` is the charter; ``SKETCH.md`` maps the modules to the laws they serve.
"""

from agent_neo.a3 import algebra, bridge, gates, lattice, laws, ops, term
from agent_neo.a3.algebra import (
    Carrier,
    Coverage,
    OnMissing,
    RollPlan,
    classify,
    diff,
    join,
    lift,
    lower,
    plan_roll,
    rank,
    rekey,
    relift,
    restrict,
    roll,
    scale,
    shift,
)
from agent_neo.a3.algebra import map as map_cells
from agent_neo.a3.algebra import slice as slice_cells
from agent_neo.a3.bridge import (
    Resolver,
    Store,
    carrier_from_instances,
    instances_from_carrier,
)
from agent_neo.a3.carrier import (
    ABSENT,
    Absent,
    Classifications,
    Coordinate,
    CoverageState,
    Dimension,
    freeze_classifications,
)
from agent_neo.a3.gates import (
    GateOutcome,
    RecomputeReason,
    Verdict,
    freshness_gate,
    gate,
    is_mature,
    lineage_gate,
    maturity_gate,
)
from agent_neo.a3.lattice import Lattice, MappingLattice
from agent_neo.a3.operators import (
    AggregateKind,
    Count,
    IllegalOperatorUse,
    Max,
    Mean,
    Min,
    Operator,
    OperatorRegistry,
    Percentile,
    Proportion,
    RatioAccumulator,
    Sketch,
    SketchFactory,
    Sum,
    WeightedMean,
)
from agent_neo.a3.ops import Ensure as EnsureContract
from agent_neo.a3.ops import Invalidate, Retire
from agent_neo.a3.product import (
    PLAIN_KEY_SCHEME,
    Ask,
    Concept,
    Field,
    FieldRole,
    Identity,
    Instance,
    KeyScheme,
    Layer,
    LifecycleStatus,
    LineageRef,
    Refuse,
    RefuseReason,
    TermLike,
    servable,
)
from agent_neo.a3.term import (
    Classify,
    Ensure,
    Env,
    Join,
    Lift,
    Lower,
    Map,
    Rekey,
    Relift,
    Restrict,
    Roll,
    Shape,
    Shift,
    Slice,
    Term,
    check_layers,
    evaluate,
    products_read,
    shape,
)

__all__ = (
    'ABSENT',
    'PLAIN_KEY_SCHEME',
    'Absent',
    'AggregateKind',
    'Ask',
    'Carrier',
    'Classifications',
    'Classify',
    'Concept',
    'Coordinate',
    'Count',
    'Coverage',
    'CoverageState',
    'Dimension',
    'Ensure',
    'EnsureContract',
    'Env',
    'Field',
    'FieldRole',
    'GateOutcome',
    'Identity',
    'IllegalOperatorUse',
    'Instance',
    'Invalidate',
    'Join',
    'KeyScheme',
    'Lattice',
    'Layer',
    'LifecycleStatus',
    'Lift',
    'LineageRef',
    'Lower',
    'Map',
    'MappingLattice',
    'Max',
    'Mean',
    'Min',
    'OnMissing',
    'Operator',
    'OperatorRegistry',
    'Percentile',
    'Proportion',
    'RatioAccumulator',
    'RecomputeReason',
    'Refuse',
    'RefuseReason',
    'Rekey',
    'Relift',
    'Resolver',
    'Restrict',
    'Retire',
    'Roll',
    'RollPlan',
    'Shape',
    'Shift',
    'Sketch',
    'SketchFactory',
    'Slice',
    'Store',
    'Sum',
    'Term',
    'TermLike',
    'Verdict',
    'WeightedMean',
    'algebra',
    'bridge',
    'carrier_from_instances',
    'check_layers',
    'classify',
    'diff',
    'evaluate',
    'freeze_classifications',
    'freshness_gate',
    'gate',
    'gates',
    'instances_from_carrier',
    'is_mature',
    'join',
    'lattice',
    'laws',
    'lift',
    'lineage_gate',
    'lower',
    'map_cells',
    'maturity_gate',
    'ops',
    'plan_roll',
    'products_read',
    'rank',
    'rekey',
    'relift',
    'restrict',
    'roll',
    'scale',
    'servable',
    'shape',
    'shift',
    'slice_cells',
    'term',
)
