"""Graph database helpers."""


from __future__ import annotations

from typing import LiteralString

from agent_neo.graph_db._core import (
    GRAPH_DB_BATCH_SIZE,
    NEO4J_CLUSTER_LEADER_SWITCH_BACKOFF_MULTIPLIER,
    NEO4J_CLUSTER_LEADER_SWITCH_MAX_ATTEMPTS,
    NEO4J_CLUSTER_LEADER_SWITCH_MAX_RETRY_DELAY_SECONDS,
    NEO4J_CLUSTER_LEADER_SWITCH_RETRY_DELAY_SECONDS,
    GraphDbConfig,
    GraphDbQueryAndReturnHeaderList,
    batched_cypher_execute,
    connect_graph_db,
    is_graph_db_connected,
    is_transient_neo4j_error,
    load_query,
    reconnect_graph_db_if_needed,
    reconnect_neo4j_driver,
    retry_neo4j_cluster_operation,
    set_label_install_callback,
)
from agent_neo.graph_db.period_rollup_bulk import (
    fetch_cache_keys_by_indexed_filters_cypher,
    fetch_hvac_hourly_summaries_by_cache_keys_cypher,
    fetch_period_rollup_cache_keys_by_spine_window_cypher,
    fetch_period_rollup_rows_by_cache_keys_cypher,
    hourly_summary_maps_from_cypher_rows,
    merge_period_rollup_rows_cypher,
    neo4j_bulk_timestamps,
    preload_hvac_hourly_summaries_by_asset_window_cypher,
    preload_meter_rollups_by_spine_window_cypher,
    preload_period_rollups_by_spine_window_cypher,
    property_maps_from_cypher_rows,
    safe_connect_relationship,
    spine_window_where_clauses,
)
from agent_neo.graph_db.query_bind import (
    LABEL_PLACEHOLDER,
    PROPERTY_PLACEHOLDER,
    WHERE_PLACEHOLDER,
    bind_label,
    bind_label_and_property,
    bind_where_clause,
)


__all__: tuple[LiteralString, ...] = (
    "DEFAULT_DELETE_CHUNK_SIZE",
    "DEFAULT_IN_CHUNK_SIZE",
    "GRAPH_DB_BATCH_SIZE",
    "LABEL_PLACEHOLDER",
    "PROPERTY_PLACEHOLDER",
    "WHERE_PLACEHOLDER",
    "NEO4J_CLUSTER_LEADER_SWITCH_BACKOFF_MULTIPLIER",
    "NEO4J_CLUSTER_LEADER_SWITCH_MAX_ATTEMPTS",
    "NEO4J_CLUSTER_LEADER_SWITCH_MAX_RETRY_DELAY_SECONDS",
    "NEO4J_CLUSTER_LEADER_SWITCH_RETRY_DELAY_SECONDS",
    "GraphDbConfig",
    "GraphDbQueryAndReturnHeaderList",
    "batched_cypher_execute",
    "bind_label",
    "bind_label_and_property",
    "bind_where_clause",
    "connect_graph_db",
    "cypher_read",
    "cypher_write",
    "fetch_cache_keys_by_indexed_filters_cypher",
    "fetch_hvac_hourly_summaries_by_cache_keys_cypher",
    "fetch_period_rollup_cache_keys_by_spine_window_cypher",
    "fetch_period_rollup_rows_by_cache_keys_cypher",
    "for_each_chunk",
    "hourly_summary_maps_from_cypher_rows",
    "is_graph_db_connected",
    "is_transient_neo4j_error",
    "load_query",
    "merge_period_rollup_rows_cypher",
    "neo4j_bulk_timestamps",
    "preload_hvac_hourly_summaries_by_asset_window_cypher",
    "preload_meter_rollups_by_spine_window_cypher",
    "preload_period_rollups_by_spine_window_cypher",
    "property_maps_from_cypher_rows",
    "reconnect_graph_db_if_needed",
    "reconnect_neo4j_driver",
    "retry_neo4j_cluster_operation",
    "safe_connect_relationship",
    "set_label_install_callback",
    "spine_window_where_clauses",
)
